# Site settings
title: "Concierge Pixel Tech Consultancy"
email: "info@conciergepixel.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: 'ConciergePixel'
github_username: 'ConciergePixel'

# Build settings
markdown: kramdown
